services:
  ai-analyzer:
    build: ./backend-ai
    container_name: sg-ai-analyzer
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DB_URL=${DB_URL}
    depends_on:
      - db
    networks:
      - sg-network

  db:
    image: postgres:15-alpine
    container_name: sg-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: guardian_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sg-network

  frontend:
    build: ./frontend
    container_name: sg-frontend
    networks:
      - sg-network

  gateway:
    image: nginx:alpine
    container_name: sg-gateway
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf # :ro 제거 (권한 문제 방지)
    depends_on:
      - ai-analyzer
    networks:
      - sg-network

networks:
  sg-network:
    driver: bridge